-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 14:35:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_livraria_virtual
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_livraria_virtual` ;

-- -----------------------------------------------------
-- Schema bd_livraria_virtual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_livraria_virtual` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_livraria_virtual` ;

-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Autor` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Cidade` (
  `idCidade` INT NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Editora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Editora` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Editora` (
  `idEditora` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Endereço` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Endereço` (
  `CEP` INT NOT NULL,
  `endereço_completo` VARCHAR(45) NULL,
  `UF_idUF` INT NOT NULL,
  `País_idPaís` INT NOT NULL,
  `Cidade_idCidade` INT NOT NULL,
  PRIMARY KEY (`CEP`),
  INDEX `fk_endereço_UF1_idx` (`UF_idUF` ASC) VISIBLE,
  INDEX `fk_endereço_País1_idx` (`País_idPaís` ASC) VISIBLE,
  INDEX `fk_endereço_Cidade1_idx` (`Cidade_idCidade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Entrega` (
  `identrega` INT NOT NULL AUTO_INCREMENT,
  `data_de_entrega` DATETIME NULL,
  `endereço_de_entrega_CEP` INT NOT NULL,
  `endereço_CEP` INT NOT NULL,
  PRIMARY KEY (`identrega`, `endereço_de_entrega_CEP`),
  INDEX `fk_Entrega_endereço1_idx` (`endereço_CEP` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Estado_civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Estado_civil` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Estado_civil` (
  `idEstado_civil` INT NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Filiação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Filiação` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Filiação` (
  `idFiliação` INT NOT NULL AUTO_INCREMENT,
  `nome_pai` VARCHAR(45) NULL,
  `nome_mae` VARCHAR(45) NULL,
  PRIMARY KEY (`idFiliação`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`FomaPagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`FomaPagamento` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`FomaPagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `forma_pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`FuncionarioResponsavel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`FuncionarioResponsavel` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`FuncionarioResponsavel` (
  `idfuncionário` INT NOT NULL AUTO_INCREMENT,
  `pedido_endereço_de_entrega_CEP` INT NOT NULL,
  `pedido_pagamento_idpagamento` INT NOT NULL,
  `pessoa_idpessoa` INT NOT NULL,
  `pessoa_endereço_de_entrega_CEP` INT NOT NULL,
  `pessoa_idpessoa1` INT NOT NULL,
  `pessoa_endereço_de_entrega_CEP1` INT NOT NULL,
  `pessoa_idpessoa2` INT NOT NULL,
  `pessoa_endereço_de_entrega_CEP2` INT NOT NULL,
  PRIMARY KEY (`idfuncionário`, `pedido_endereço_de_entrega_CEP`, `pedido_pagamento_idpagamento`, `pessoa_idpessoa`, `pessoa_endereço_de_entrega_CEP`),
  INDEX `fk_funcionário_pessoa2_idx` (`pessoa_idpessoa1` ASC, `pessoa_endereço_de_entrega_CEP1` ASC) VISIBLE,
  INDEX `fk_FuncionárioResponsável_pessoa1_idx` (`pessoa_idpessoa2` ASC, `pessoa_endereço_de_entrega_CEP2` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Livro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Livro` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Livro` (
  `titulo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `editora` VARCHAR(45) NOT NULL,
  `ISBN` VARCHAR(30) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `valor_idvalor` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  `Editora_idEditora` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `ValorLivro_idvalor` INT NOT NULL,
  PRIMARY KEY (`ISBN`, `valor_idvalor`),
  INDEX `fk_livro_Autor1_idx` (`Autor_idAutor` ASC) VISIBLE,
  INDEX `fk_livro_Editora1_idx` (`Editora_idEditora` ASC) VISIBLE,
  INDEX `fk_livro_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  INDEX `fk_Livro_ValorLivro1_idx` (`ValorLivro_idvalor` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Naturalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Naturalidade` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Naturalidade` (
  `idNaturalidade` INT NOT NULL,
  `descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idNaturalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`País`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`País` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`País` (
  `idPaís` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaís`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `preço` VARCHAR(45) NOT NULL,
  `cliente_nome1` VARCHAR(45) NOT NULL,
  `livro_ISBN` VARCHAR(30) NOT NULL,
  `entrega_identrega` INT NOT NULL,
  `entrega_endereço_de_entrega_CEP` INT NOT NULL,
  `livro_ISBN1` VARCHAR(30) NOT NULL,
  `livro_valor_idvalor` INT NOT NULL,
  `FomaPagamento_idpagamento` INT NOT NULL,
  `funcionário_idfuncionário` INT NOT NULL,
  `funcionário_pedido_endereço_de_entrega_CEP` INT NOT NULL,
  `funcionário_pedido_pagamento_idpagamento` INT NOT NULL,
  `funcionário_pessoa_idpessoa` INT NOT NULL,
  `funcionário_pessoa_endereço_de_entrega_CEP` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `cliente_nome1`, `livro_ISBN`),
  INDEX `fk_pedido_entrega1_idx` (`entrega_identrega` ASC, `entrega_endereço_de_entrega_CEP` ASC) VISIBLE,
  INDEX `fk_pedido_livro1_idx` (`livro_ISBN1` ASC, `livro_valor_idvalor` ASC) VISIBLE,
  INDEX `fk_Pedido_FomaPagamento1_idx` (`FomaPagamento_idpagamento` ASC) VISIBLE,
  INDEX `fk_Pedido_funcionário1_idx` (`funcionário_idfuncionário` ASC, `funcionário_pedido_endereço_de_entrega_CEP` ASC, `funcionário_pedido_pagamento_idpagamento` ASC, `funcionário_pessoa_idpessoa` ASC, `funcionário_pessoa_endereço_de_entrega_CEP` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Sexo` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Sexo` (
  `idSexo` INT NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`Telefone` (
  `número` INT NOT NULL,
  PRIMARY KEY (`número`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`UF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`UF` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`UF` (
  `idUF` INT NOT NULL,
  `descrição` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`ValorLivro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`ValorLivro` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`ValorLivro` (
  `idvalor` INT NOT NULL AUTO_INCREMENT,
  `forma_de_pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvalor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_livraria_virtual`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_livraria_virtual`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `bd_livraria_virtual`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `identidade` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `escolaridade` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `endereço_CEP` INT NOT NULL,
  `Sexo_idSexo` INT NOT NULL,
  `Estado_civil_idEstado_civil` INT NOT NULL,
  `Naturalidade_idNaturalidade` INT NOT NULL,
  `Telefone_número` INT NOT NULL,
  `Filiação_idFiliação` INT NOT NULL,
  PRIMARY KEY (`idpessoa`),
  INDEX `fk_pessoa_endereço1_idx` (`endereço_CEP` ASC) VISIBLE,
  INDEX `fk_pessoa_Sexo1_idx` (`Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_pessoa_Estado_civil1_idx` (`Estado_civil_idEstado_civil` ASC) VISIBLE,
  INDEX `fk_pessoa_Naturalidade1_idx` (`Naturalidade_idNaturalidade` ASC) VISIBLE,
  INDEX `fk_pessoa_Telefone1_idx` (`Telefone_número` ASC) VISIBLE,
  INDEX `fk_pessoa_Filiação1_idx` (`Filiação_idFiliação` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into `autor`
(`idAutor`,`nome`) 
values
(default, 'Cleiton'),
(default, 'João'),
(default, 'Lucas'),
(default, 'Daniel'),
(default, 'Rafael');
insert into `categoria`
(`idcategoria`,`tipo`)
values
(default, ‘Infantil’),
(default, ‘Técnico ’),
(default, ‘Ficção’),
(default, ‘Não ficção’),
(default, ‘Técnico’);

insert into `cidade`
(`idCidade`,`descrição`)
values
(default, ‘Brasília’),
(default, ‘Goiânia’),
(default, ‘Rio de Janeiro’),
(default, ‘São Paulo’),
(default, ‘Belo horizonte’);

insert into `cliente`
(`idCliente`,`pessoa_idpessoa`,`Pedido_idpedido`,`Pedido_cliente_nome1`,`Pedido_livro_ISBN`)
values
 
insert into`editora`
(`idEditora`,`nome`)
values
(default, ‘Pinguim’),
(default, ‘Folha’),
(default, ‘Travessa’),
(default, ‘Darkside’),
(default, ‘Arqueiro’);

insert into`endereço`
(`CEP`,`endereço_completo`,`UF_idUF`,`País_idPaís`,`Cidade_idCidade`)
values
(99999999, ‘Setor Sul’,default,default,default),
(88888888, ‘Setor Norte’,default,default,default),
(77777777, ‘Setor Leste’,default,default,default),
(66666666, ‘Setor Oeste’,default,default,default),
(55555555, ‘Setor Sudeste’,default,default,default);

insert into`entrega`
(`identrega`,`data_de_entrega`,`endereço_de_entrega_CEP`,`endereço_CEP`)
values
(default, ‘01/01/2022’,default,default),
(default, ‘02/01/2022’,default,default),
(default, ‘03/01/2022’,default,default),
(default, ‘04/01/2022’,default,default),
(default, ‘05/01/2022’,default,default);

insert into`estado_civil`
(`idEstado_civil`,`descrição`)
values
(default, ‘Solteiro’),
(default, ‘Casado’),
(default, ‘Divorciado’),
(default, ‘Viúvo’),
(default, ‘Solteiro’);
insert into`filiação`
(`idFiliação`,`nome_pai`,`nome_mãe`)
values
 (default, ‘Jorge’, ‘Carla’),
(default, ‘João ’, ‘Daniela’),
(default, ‘Carlos’, ‘Tereza’),
(default, ‘Mauro’, ‘Ana’),
(default, ‘Pedro’, ‘Isabela’);
insert into`formapagamento`
(`idpagamento`,`forma_pagamento`)
values
(default, ‘Pix’),
(default, ‘Boleto’),
(default, ‘Cartão’),
(default, ‘Pix’),
(default, ‘Cartão’);

insert into`funcionarioresponsavel`
(`idfuncionário`,`pedido_endereço_de_entrega_CEP`,`pedido_pagamento_idpagamento`,`pessoa_idpessoa`,`pessoa_endereço_de_entrega_CEP`,`pessoa_idpessoa1`,`pessoa_endereço_de_entrega_CEP1`,`pessoa_idpessoa2`,`pessoa_endereço_de_entrega_CEP2`)
values
insert into`livro`
(`titulo`,`autor`,`editora`,`ISBN`,`categoria`,`valor_idvalor`,`Autor_idAutor`,`Editora_idEditora`,`categoria_idcategoria`,`valorLivro_idvalor`)
values
 
insert into`naturalidade`
(`idNaturalidade`,`descrição`)
values
 
insert into`país`
(`idPaís`,`nome`)
values
insert into`pedido`
(`idpedido`,`preço`,`cliente_nome1`
`livro_ISBN`,`entrega_identrega`,`entrega_endereço_de_entrega_CEP`,`livro_ISBN1`,`livro_valor_idvalor`,`FormaPagamento_idpagamento`,`funcionário_idfuncionário`,`funcionário_pedido_endereço_de_entrega_CEP`,`funcionário_pedido_pagamento_idpagamento`,`funcionário_pedido_idpessoa`,`funcionário_pessoa_endereço_de_entrega_CEP`)
values
insert into`pessoa`
(`idpessoa`,`nome`,`CPF`,`identidade`,`email`,`escolaridade`,`cargo`,`endereço_CEP`,`Sexo_idSexo``Estado_civil_idEstado_civil`,`Naturalidade_idNaturalidade`,`Telefone_número`,`Filiação_idFiliação`)
 
insert into`sexo`
(`idSexo`,`descrição`)
values
 
insert into`telefone`
(`número`)
values
 
 
insert into`uf`
(`idUF`,`descrição`)
values
 
 
insert into`valorlivro`
(`idValor`,`forma_de_pagamento`)
